imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

parameters:
  database_driver:   pdo_mysql
  database_host:     alpha-db.eardish.net
  database_port:     ~
  database_name:     alphawebdb
  database_user:     alphawebdb
  database_password: GLLTtpr5dbKLL
  
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
          enum: string
        
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
