<?php

namespace EarDish\MFP\APIHandlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRepository extends EntityRepository
{
    public function findOneByTypeAndTypeId($type, $typeid) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT a 
                            FROM EarDishMFPAPIHandlerBundle:Audio a 
                            WHERE a.type = :type AND a.typeId = :id
                            ORDER BY a.dateModified DESC')
                ->setFirstResult(0)
                ->setMaxResults(1)
                ->setParameter("type", $type)
                ->setParameter("id", $typeid)
                ->getSingleResult();
    }
    
    public function findOneById($id) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT a 
                            FROM EarDishMFPAPIHandlerBundle:Audio a 
                            WHERE a.id = :id')
                ->setParameter("id", $id)
                ->getSingleResult();
    }
}
