<?php

namespace EarDish\MFP\APIHandlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioFormatRepository extends EntityRepository
{
    public function findOneByIdAndFormat($id, $format) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT a 
                            FROM EarDishMFPAPIHandlerBundle:AudioFormat a 
                            WHERE a.format = :format AND a.audio = :id')
                ->setParameter("format", $format)
                ->setParameter("id", $id)
                ->getSingleResult();
    }
}
