<?php

namespace EarDish\MFP\APIHandlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findOneByTypeAndTypeId($type, $typeid) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT i 
                            FROM EarDishMFPAPIHandlerBundle:Image i 
                            WHERE i.type = :type AND i.typeId = :id
                            ORDER BY i.dateModified DESC')
                ->setFirstResult(0)
                ->setMaxResults(1)
                ->setParameter("type", $type)
                ->setParameter("id", $typeid)
                ->getSingleResult();
    }
    
    public function findOneById($id) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT i 
                            FROM EarDishMFPAPIHandlerBundle:Image i 
                            WHERE i.id = :id')
                ->setParameter("id", $id)
                ->getSingleResult();
    }
}
