<?php

namespace EarDish\MFP\APIHandlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
    public function findOneByKey($key) {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT s 
                            FROM EarDishMFPAPIHandlerBundle:Settings s 
                            WHERE s.key = :key')
                ->setParameter("key", $key)
                ->getSingleResult();
    }
}
